gmf_devis_homepage:
    path:     /
    defaults: { _controller: GMFDevisBundle:Devis:index }

gmf_devis_order:
    path:     /order
    defaults: { _controller: GMFDevisBundle:Devis:order }

gmf_devis_thanks:
    path:     /thanks
    defaults: { _controller: GMFDevisBundle:Devis:thanks}