#Page d'accueil du site
gmf_devis_home:
    path:     /
    defaults: { _controller: GMFDevisBundle:Devis:index }


#Formulaire de réservation du devis
gmf_devis_order:
    path:     /commande
    defaults: { _controller: GMFDevisBundle:Devis:order }

#Page des modules
gmf_devis_modules:
    path:   /modules
    defaults: { _controller: GMFDevisBundle:Devis:modules}

# Remerciement après demande d'un devis
gmf_devis_thanks:
    path:     /thanks
    defaults: { _controller: GMFDevisBundle:Devis:thanks}