#Page d'accueil du site
gmf_devis_home:
    path:     /
    defaults: { _controller: GMFDevisBundle:Devis:index }


#Formulaire de réservation du devis
gmf_devis_order:
    path:     /order
    defaults: { _controller: GMFDevisBundle:Devis:order }

# Remerciement après demande d'un devis
gmf_devis_thanks:
    path:     /thanks
    defaults: { _controller: GMFDevisBundle:Devis:thanks}

gmf_administration:
    path:   /admin
    defaults: { _controller: GMFDevisBundle:Devis:admin}