services:
  gmf_devis.orderAction:
    class: GMF\DevisBundle\Services\GMFOrderAction

  gmf_devis.devisAction:
    class: GMF\DevisBundle\Services\GMFDevisAction

  gmf_devis.emailAction:
    class:  GMF\DevisBundle\Services\GMFEmailAction
    arguments:
      - "@twig"
    
#    gmf_devis.example:
#        class: GMF\DevisBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
