gmf_devis:
    resource: "@GMFDevisBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: GMFUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
