# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    GMF\UserBundle\Entity\User: plaintext

  role_hierarchy:
    ROLE_ADMIN:       [ROLE_EDITEUR]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main: 
      entity:
        class:    GMF\UserBundle\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern:    ^/
      anonymous:  true
      provider:   main
      form_login:
        login_path: login
        check_path: login_check
      logout:
        path:       logout
        target:     login

  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

