<?php

namespace GMF\DevisBundle\Repository;

/**
 * ModulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModulesRepository extends \Doctrine\ORM\EntityRepository
{
}
