gmf_admin_home:
    path: /
    defaults: { _controller: GMFAdminBundle:Admin:devis}
    
gmf_admin_view_devis:
    path:  /devis/view/{id}
    defaults: { _controller: GMFAdminBundle:Admin:view_devis}

gmf_admin_delete_devis:
    path: /devis/delete/{id}
    defaults: { _controller: GMFAdminBundle:Admin:delete_devis}
