gmf_admin_home:
    path: /
    defaults: { _controller: GMFAdminBundle:Admin:devis}
    
gmf_admin_view_devis:
    path:  /view/devis/{id}
    defaults: { _controller: GMFAdminBundle:Admin:view_devis}
