gmf_admin_home:
    path: /
    defaults: { _controller: GMFAdminBundle:Admin:devis}
    
gmf_admin_view_devis:
    path:  /devis/view/{id}
    defaults: { _controller: GMFAdminBundle:Admin:view_devis}

gmf_admin_delete_devis:
    path: /devis/delete/{id}
    defaults: { _controller: GMFAdminBundle:Admin:delete_devis}

gmf_admin_modules:
    path: /modules 
    defaults: { _controller: GMFAdminBundle:Admin:modules}

gmf_admin_modules_add:
    path: /modules/add 
    defaults: { _controller: GMFAdminBundle:Admin:modules_add}

gmf_admin_users:
    path : /users 
    defaults: { _controller: GMFAdminBundle:Admin:users}

gmf_admin_user_delete:
    path: /user/delete/{username}
    defaults: { _controller: GMFAdminBundle:Admin:delete_user}
